require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable
  SuggestExtensions: false

Layout/ExtraSpacing:
  Exclude:
    - 'ruby_magic_link.gemspec'

Layout/LineLength:
  Exclude:
    - 'spec/**/*'

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver
  Exclude:
    - 'spec/**/*'

Layout/SpaceAroundOperators:
  Exclude:
    - 'ruby_magic_link.gemspec'

Metrics/BlockLength:
  Max: 20
  AllowedMethods: [describe, context]

Metrics/MethodLength:
  Max: 20

Naming/MethodParameterName:
  AllowedNames:
    - iv

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 10

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false
