name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: ['3.3', '3.2', '3.1']

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Install dependencies
        run: bundle install
      - name: Linters
        run: bundle exec rubocop --parallel
      - name: Rbs collections
        run: rbs collection install
      - name: Typechecking
        run: bundle exec steep check
      - name: Run tests
        run: bundle exec rspec